---
development:
  dialect: postgres
  database: recipe-dev
  user: recipe-dev
  password: mn2PoBaz
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://recipe-test:mn2PoBaz@127.0.0.1:5432/recipe-test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://recipe-prod:mn2PoBaz@127.0.0.1:5432/recipe-prod?sslmode=disable"}}
